#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-msgpack
Version  : 1.0.3
Release  : 28
URL      : https://files.pythonhosted.org/packages/61/3c/2206f39880d38ca7ad8ac1b28d2d5ca81632d163b2d68ef90e46409ca057/msgpack-1.0.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/61/3c/2206f39880d38ca7ad8ac1b28d2d5ca81632d163b2d68ef90e46409ca057/msgpack-1.0.3.tar.gz
Summary  : MessagePack (de)serializer.
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-msgpack-filemap = %{version}-%{release}
Requires: pypi-msgpack-lib = %{version}-%{release}
Requires: pypi-msgpack-license = %{version}-%{release}
Requires: pypi-msgpack-python = %{version}-%{release}
Requires: pypi-msgpack-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# MessagePack for Python
[![Build Status](https://travis-ci.org/msgpack/msgpack-python.svg?branch=master)](https://travis-ci.org/msgpack/msgpack-python)
[![Documentation Status](https://readthedocs.org/projects/msgpack-python/badge/?version=latest)](https://msgpack-python.readthedocs.io/en/latest/?badge=latest)

%package filemap
Summary: filemap components for the pypi-msgpack package.
Group: Default

%description filemap
filemap components for the pypi-msgpack package.


%package lib
Summary: lib components for the pypi-msgpack package.
Group: Libraries
Requires: pypi-msgpack-license = %{version}-%{release}
Requires: pypi-msgpack-filemap = %{version}-%{release}

%description lib
lib components for the pypi-msgpack package.


%package license
Summary: license components for the pypi-msgpack package.
Group: Default

%description license
license components for the pypi-msgpack package.


%package python
Summary: python components for the pypi-msgpack package.
Group: Default
Requires: pypi-msgpack-python3 = %{version}-%{release}

%description python
python components for the pypi-msgpack package.


%package python3
Summary: python3 components for the pypi-msgpack package.
Group: Default
Requires: pypi-msgpack-filemap = %{version}-%{release}
Requires: python3-core
Provides: pypi(msgpack)

%description python3
python3 components for the pypi-msgpack package.


%prep
%setup -q -n msgpack-1.0.3
cd %{_builddir}/msgpack-1.0.3
pushd ..
cp -a msgpack-1.0.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1653344907
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-msgpack
cp %{_builddir}/msgpack-1.0.3/COPYING %{buildroot}/usr/share/package-licenses/pypi-msgpack/175e59be229a5bedc6be93e958a970385bb04a62
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot}/usr/share/clear/optimized-elf/ %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-pypi-msgpack

%files lib
%defattr(-,root,root,-)
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-msgpack/175e59be229a5bedc6be93e958a970385bb04a62

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
